"""sync storage — 同期ストアのインターフェイス（async 側の同期版）。

- [SyncKeyValueStore] … [KeyValueStore] の同期版（put/get がメイン）。
- [SyncFileStore] … [FileStore] の同期版（`open` で [SyncFileObject] を取得）。

当面の実装は async_to_sync_storage のブリッジが担うが、将来ループを外して性能を取りたい
ときは、これらのインターフェイスに沿った手書きの同期バックエンドを足せる（差し替え可能）。
"""

from collections.abc import Iterator
from typing import Protocol

from .async_storage import FileInfo


class SyncKeyValueStore(Protocol):
    def put(self, key: str, value: bytes) -> None: ...
    def get(self, key: str) -> bytes | None: ...
    def iter(self) -> Iterator[FileInfo]: ...
    def list(self, limit: int = 10) -> list[FileInfo]: ...
    def exists(self, key: str) -> bool: ...
    def delete(self, key: str) -> None: ...
    def cp(self, src: str, dst: str) -> None: ...
    def mv(self, src: str, dst: str) -> None: ...
    def connect(self) -> None: ...


class SyncFileObject(Protocol):
    """`SyncFileStore.open` が返すファイルオブジェクト（ストリーム）。"""

    def read(self, size: int = -1) -> bytes: ...
    def write(self, data: bytes) -> int: ...
    def close(self) -> None: ...
    def __enter__(self) -> SyncFileObject: ...
    def __exit__(self, *exc: object) -> None: ...


class SyncFileStore(Protocol):
    """`open` でファイルオブジェクトを取得するストリーム指向のストア（同期版）。"""

    def open(self, filename: str, mode: str = "rb") -> SyncFileObject: ...
