# """sync storage — 同期ストアのインターフェイス（async 側の同期版）。

# - [SyncKeyValueStore] … [KeyValueStore] の同期版（put/get がメイン）。
# - [SyncFileStore] … [FileStore] の同期版（`open` で [SyncFileObject] を取得）。

# 当面の実装は [AsyncToSyncKeyValueStore] のブリッジが担うが、将来ループを外して性能を取りたい
# ときは、これらのインターフェイスに沿った手書きの同期バックエンドを足せる（差し替え可能）。
# """

# from collections.abc import Iterator
# from typing import Protocol, TypedDict

# # class FileInfo(TypedDict):
# #     filename: str
# #     size: int

# # class FileObject(Protocol):
# #     """`FileStore.open_reader`/`open_writer` が返すファイルオブジェクト（ストリーム）。"""

# #     async def read(self, size: int = -1) -> bytes: ...
# #     async def write(self, data: bytes) -> int: ...
# #     async def close(self) -> None: ...
# #     async def __aenter__(self) -> "FileObject": ...
# #     async def __aexit__(self, *exc: object) -> None: ...


# # class AsyncKeyValueStore(Protocol):
# #     async def put(self, key: str, value: bytes) -> None: ...
# #     async def get_or_raise(self, key: str) -> bytes: ...
# #     async def get(self, key: str, default: bytes | None = None) -> bytes | None: ...
# #     async def iter_all(self, limit: int | None = None) -> AsyncIterable[FileInfo]: ...
# #     async def list_all(self, limit: int | None = None) -> list[FileInfo]: ...
# #     async def exists(self, key: str) -> bool: ...
# #     async def delete(self, key: str) -> None: ...
# #     # async def delete_all(self) -> None: ...
# #     async def cp(self, src: str, dst: str) -> None: ...
# #     async def mv(self, src: str, dst: str) -> None: ...
# #     async def connect(self) -> None: ...
# #     async def aclose(self) -> None: ...


# class AsyncFileStore(AsyncKeyValueStore, Protocol):
#     """`open_reader`/`open_writer` でファイルを取得するストア（同期版・バイナリ専用）。"""

#     async def open_reader(self, filename: str) -> FileObject: ...
#     async def open_writer(self, filename: str) -> FileObject: ...


# class SyncFileObject(Protocol):
#     """`SyncFileStore.open` が返すファイルオブジェクト（ストリーム）。"""

#     def read(self, size: int = -1) -> bytes: ...
#     def write(self, data: bytes) -> int: ...
#     def close(self) -> None: ...
#     def __enter__(self) -> SyncFileObject: ...
#     def __exit__(self, *exc: object) -> None: ...


# class SyncKeyValueStore(Protocol):
#     def put(self, key: str, value: bytes) -> None: ...
#     def get_or_raise(self, key: str) -> bytes: ...
#     def get(self, key: str, default: bytes | None = None) -> bytes | None: ...
#     def iter_all(self, limit: int | None = None) -> Iterator[FileInfo]: ...
#     def list_all(self, limit: int | None = None) -> list[FileInfo]: ...
#     def exists(self, key: str) -> bool: ...
#     def delete(self, key: str) -> None: ...
#     def cp(self, src: str, dst: str) -> None: ...
#     def mv(self, src: str, dst: str) -> None: ...
#     def connect(self) -> None: ...


# class SyncFileStore(SyncKeyValueStore, Protocol):
#     """`open_reader`/`open_writer` でファイルを取得するストア（同期版・バイナリ専用）。"""

#     def open_reader(self, filename: str) -> SyncFileObject: ...
#     def open_writer(self, filename: str) -> SyncFileObject: ...
